// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TradeLedger.Infrastructure.Database;

#nullable disable

namespace TradeLedger.Infrastructure.Database.Migrations
{
    [DbContext(typeof(TradeLedgerDbContext))]
    partial class TradeLedgerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TradeLedger.Infrastructure.Database.Entities.FillEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ExecutedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("executed_at");

                    b.Property<decimal>("Price")
                        .HasPrecision(28, 8)
                        .HasColumnType("numeric(28,8)")
                        .HasColumnName("price");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(28, 8)
                        .HasColumnType("numeric(28,8)")
                        .HasColumnName("quantity");

                    b.Property<string>("Side")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("side");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("symbol");

                    b.HasKey("Id")
                        .HasName("pk_fills");

                    b.HasIndex("ExecutedAt")
                        .HasDatabaseName("ix_fills_executed_at");

                    b.HasIndex("ProcessedAt")
                        .HasDatabaseName("ix_fills_processed_at");

                    b.HasIndex("Symbol")
                        .HasDatabaseName("ix_fills_symbol");

                    b.ToTable("fills", (string)null);
                });

            modelBuilder.Entity("TradeLedger.Infrastructure.Database.Entities.LotEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("OpenedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("opened_at");

                    b.Property<decimal>("RemainingQuantity")
                        .HasPrecision(28, 8)
                        .HasColumnType("numeric(28,8)")
                        .HasColumnName("remaining_quantity");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("symbol");

                    b.Property<decimal>("UnitCost")
                        .HasPrecision(28, 8)
                        .HasColumnType("numeric(28,8)")
                        .HasColumnName("unit_cost");

                    b.HasKey("Id")
                        .HasName("pk_lots");

                    b.HasIndex("Symbol")
                        .HasDatabaseName("ix_lots_symbol");

                    b.HasIndex("Symbol", "OpenedAt")
                        .HasDatabaseName("ix_lots_symbol_opened_at");

                    b.HasIndex("Symbol", "RemainingQuantity")
                        .HasDatabaseName("ix_lots_symbol_remaining_quantity");

                    b.ToTable("lots", (string)null);
                });

            modelBuilder.Entity("TradeLedger.Infrastructure.Database.Entities.RealisedPnlEntryEntity", b =>
                {
                    b.Property<Guid>("FillId")
                        .HasColumnType("uuid")
                        .HasColumnName("fill_id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(28, 8)
                        .HasColumnType("numeric(28,8)")
                        .HasColumnName("amount");

                    b.Property<DateTimeOffset>("RealisedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("realised_at");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("symbol");

                    b.HasKey("FillId")
                        .HasName("pk_realised_pnl_entries");

                    b.HasIndex("Symbol", "RealisedAt")
                        .HasDatabaseName("ix_realised_pnl_entries_symbol_realised_at");

                    b.ToTable("realised_pnl_entries", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
