// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TradeLedger.Database;

#nullable disable

namespace TradeLedger.Database.Migrations
{
    [DbContext(typeof(TradeLedgerDbContext))]
    [Migration("20260902083824_RemoveUnusedPositionState")]
    partial class RemoveUnusedPositionState
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TradeLedger.Database.Entities.FillEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ExecutedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("executed_at");

                    b.Property<decimal>("Price")
                        .HasPrecision(28, 8)
                        .HasColumnType("numeric(28,8)")
                        .HasColumnName("price");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(28, 8)
                        .HasColumnType("numeric(28,8)")
                        .HasColumnName("quantity");

                    b.Property<string>("Side")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("side");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("symbol");

                    b.HasKey("Id")
                        .HasName("pk_fills");

                    b.HasIndex("Symbol", "ProcessedAt")
                        .HasDatabaseName("ix_fills_symbol_processed_at");

                    b.HasIndex("Symbol", "ExecutedAt", "Id")
                        .HasDatabaseName("ix_fills_symbol_executed_at_id");

                    b.ToTable("fills", (string)null);
                });

            modelBuilder.Entity("TradeLedger.Database.Entities.LotEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("OpenedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("opened_at");

                    b.Property<decimal>("RemainingQuantity")
                        .HasPrecision(28, 8)
                        .HasColumnType("numeric(28,8)")
                        .HasColumnName("remaining_quantity");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("symbol");

                    b.Property<decimal>("UnitCost")
                        .HasPrecision(28, 8)
                        .HasColumnType("numeric(28,8)")
                        .HasColumnName("unit_cost");

                    b.HasKey("Id")
                        .HasName("pk_lots");

                    b.HasIndex("Symbol")
                        .HasDatabaseName("ix_lots_symbol");

                    b.HasIndex("Symbol", "RemainingQuantity")
                        .HasDatabaseName("ix_lots_symbol_remaining_quantity");

                    b.HasIndex("Symbol", "OpenedAt", "Id")
                        .HasDatabaseName("ix_lots_symbol_opened_at_id");

                    b.ToTable("lots", (string)null);
                });

            modelBuilder.Entity("TradeLedger.Database.Entities.PositionEntity", b =>
                {
                    b.Property<string>("Symbol")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("symbol");

                    b.Property<decimal>("RealisedPnl")
                        .HasPrecision(28, 8)
                        .HasColumnType("numeric(28,8)")
                        .HasColumnName("realised_pnl");

                    b.HasKey("Symbol")
                        .HasName("pk_positions");

                    b.ToTable("positions", (string)null);
                });

            modelBuilder.Entity("TradeLedger.Database.Entities.RealisedPnlEntryEntity", b =>
                {
                    b.Property<Guid>("FillId")
                        .HasColumnType("uuid")
                        .HasColumnName("fill_id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(28, 8)
                        .HasColumnType("numeric(28,8)")
                        .HasColumnName("amount");

                    b.Property<DateTimeOffset>("RealisedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("realised_at");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("symbol");

                    b.HasKey("FillId")
                        .HasName("pk_realised_pnl_entries");

                    b.HasIndex("Symbol", "RealisedAt")
                        .HasDatabaseName("ix_realised_pnl_entries_symbol_realised_at");

                    b.ToTable("realised_pnl_entries", (string)null);
                });

            modelBuilder.Entity("TradeLedger.Database.Entities.LotEntity", b =>
                {
                    b.HasOne("TradeLedger.Database.Entities.FillEntity", null)
                        .WithMany()
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_lots_fills_id");
                });

            modelBuilder.Entity("TradeLedger.Database.Entities.RealisedPnlEntryEntity", b =>
                {
                    b.HasOne("TradeLedger.Database.Entities.FillEntity", null)
                        .WithMany()
                        .HasForeignKey("FillId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_realised_pnl_entries_fills_fill_id");
                });
#pragma warning restore 612, 618
        }
    }
}
